USE QUANLYDAILY
GO

CREATE TABLE BAOCAODOANHSO (
    MaBCDS VARCHAR(10) NOT NULL PRIMARY KEY,
    Thang INT,
    Nam INT,
    TongDoanhThu FLOAT
);
GO
ALTER TABLE BAOCAODOANHSO
ADD CONSTRAINT CHK_Thang CHECK (Thang BETWEEN 1 AND 12);
GO
ALTER TABLE BAOCAODOANHSO
ADD CONSTRAINT CHK_Nam CHECK (Nam >= 0);
GO
ALTER TABLE BAOCAODOANHSO
ADD CONSTRAINT CHK_TongDoanhThu CHECK (TongDoanhThu >= 0);
GO

--------------------------------------------

CREATE TABLE CT_BCDOANHSO (
    MaBCDS VARCHAR(10) NOT NULL,
    MaDaiLy VARCHAR(10) NOT NULL,
    SoLuongPhieuXuat INT,
    TongTriGia FLOAT,
    TiLe FLOAT,
  CONSTRAINT PK_CTBCDOANHSO PRIMARY KEY(MaBCDS, MaDaiLy),

   
    CONSTRAINT FK_CT_BCDOANHSO_MaBCDS FOREIGN KEY (MaBCDS) REFERENCES BAOCAODOANHSO(MaBCDS),
    CONSTRAINT FK_CT_BCDOANHSO_MaDaiLy FOREIGN KEY (MaDaiLy) REFERENCES DAILY(MaDaiLy)
);
GO

-------------------------------------

ALTER TABLE CT_BCDOANHSO
ADD CONSTRAINT CHK_SoLuongPhieuXuat CHECK (SoLuongPhieuXuat >= 0);
ALTER TABLE CT_BCDOANHSO
ADD CONSTRAINT CHK_TongTriGia CHECK (TongTriGia >= 0);
ALTER TABLE CT_BCDOANHSO
ADD CONSTRAINT CHK_TiLe CHECK (TiLe >= 0 AND TiLe <= 1);
GO
-- trigger 
CREATE TRIGGER Trigger_Update_TongDoanhThu
ON CT_BCDOANHSO
AFTER INSERT, UPDATE , DELETE
AS
BEGIN
    DECLARE @MaBCDS varchar(10);
    DECLARE @TongDoanhThu float;

    SELECT @MaBCDS = MaBCDS FROM inserted;

    SELECT @TongDoanhThu = SUM(TongTriGia)
    FROM CT_BCDOANHSO
    WHERE MaBCDS = @MaBCDS;

    UPDATE BAOCAODOANHSO
    SET TongDoanhThu = @TongDoanhThu
    WHERE MaBCDS = @MaBCDS;
END;
